# Generated by Django 4.2.7 on 2025-10-07 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_doctor_bio_doctor_experience_years_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
    ]
